### ISSUE TITLE
Output summary

### ISSUE THREAD

**Issue by TaylorOshan** [pysal/mgwr#17]
It would be good to have a summary function that constructed a text statement with a summary of the GWR/MGWR results that could be printed or saves to file, such as is done in GWR4/GWmodel.

**Comment by weikang9009** [comment]
I think I have one when I was writing the MGWR GUI a long time ago. Let me dig it.

**Comment by TaylorOshan** [comment]
That would be great! Could be good to mention and highlight it in the JSS manuscript if we have it updated for both gwr/mgwr.

**Comment by Ziqi-Li** [comment]
Hi
I have previously made one summary function for the GUI, which is based on Wei's summary code and compatible with our current APIs.

It looks like [this](https://gist.github.com/Ziqi-Li/7b9e9e6306a42c883ffd87b5b0c8d3cc). 

But two things not sure how to deal with:
1. Do we need to output summary for global regression? It makes sense to me to put the summary function into `GWRResults` class as `GWRResults.summary`. And maybe only output GWR results?

2. Since our interface takes numpy array, we do not have variable names, and they may be needed in the summary. Any solution?

**Comment by TaylorOshan** [comment]
On 1, I think it would be good to have. Could utilize ``spglm``, since its already a dependency and include with the output from ``GWRResults.summary``.

On 2, I think it makes sense to have a ``field_name`` parameter that accepts a list of names either in the ``GWR`` class or to ``GWRResults.summary`` method. Could actually pass it to either of those two and use it if it is available. If not, could auto-generate placeholder names like x1, x2, x3, etc.

**Comment by Ziqi-Li** [comment]
Shipped with #18. 
Hi @TaylorOshan, do you mind adding the aicc for global glm in `spglm`? I could only find aic and bic but not aicc. It would be easier if you could do a quick PR to `spglm`, I'm less familiar with that lib. It would be good to have the aicc in global regression summary output.

**Comment by TaylorOshan** [comment]
I'm a bit apprehensive to add it to spglm because I don't think it is used for GLM's outside of the GWR framework. Perhaps we could generalize the AICc in ``diagnostics.py`` to also take a ``GLMResults`` class by adding a tr_S attribute?. Then the ``AICc`` could be computed on a global and GWR/MGWR models.

**Comment by TaylorOshan** [comment]
Done in spglm/#7, should allow aicc to be calculated for GLMResults object.
--

**Comment by TaylorOshan** [comment]
Satisfied by #18
