### ISSUE TITLE
Distance matrix calculation is not vectorized for lat, lon (spherical) coordinates

### ISSUE THREAD

**Issue by TristanBoudreault** [pysal/mgwr#49]
I'm doing a GWR model on 13,000 observations with longitude, latitudes. Instantiating the model takes over 15 minutes on a Macbook Pro 2016. I dug a bit and narrowed it down to the distance calculation.

This section of the code could be drastically faster if it was vectorized instead of doing a vanilla python loop:
https://github.com/pysal/mgwr/blob/3bdfdf275716aefef4561decee6ec078da4259d4/mgwr/kernels.py#L82-L84

I can put together a PR if you want.

**Comment by Ziqi-Li** [comment]
Hi @TristanBoudreault ,
Thanks for pointing this out. I agree and welcome to submit a PR. At a later point, we might not store the entire weight matrix at all, since it is a n by n matrix and eats a lot of space to store (when n is large). Possibly, we could just compute each row of the weight matrix locally.

**Comment by Ziqi-Li** [comment]
With a new PR #52 , the kernel is computed locally at each location ([i.e.](https://github.com/pysal/mgwr/blob/eae8ac3d61ecbbba60b180e9ed8bab074bfb3522/mgwr/kernels.py#L19)), then no vectorization is needed. I'm closing this.
