### ISSUE TITLE
whether the calculation results in the MGWR and GWR4 are the same?

### ISSUE THREAD

**Issue by binbin110** [pysal/mgwr#92]
when i use MGWR software to calculate GWR , it will report an error "ERROR:root:Matrix is singular.". But if i use GWR4 to run used the same data, it can run. 
i want to know, whether the calculation results in the two software are the same?

**Comment by Ziqi-Li** [comment]
Hello @binbin110,

It may be slightly different if you use golden-section search since the lower and upper bound are different than theses in GWR4 (well, I suspect this, but I don't have access to the code in GWR4). The results should be consistent if you use a pre-defined bandwidth. If you do see other differences, feel free to attach a copy of the data, I could look into this.

Cheers,
Ziqi

**Comment by binbin110** [comment]
Hello @Ziqi-Li ，

Thanks for your reply.  When i use MGWR software(golden-section) to calculate GWR , it will  report an error, as the picture,![error](https://user-images.githubusercontent.com/38236412/116215603-6d81bd80-a77a-11eb-92dd-fa5388425372.jpg).When i use the pre-defined bandwidth( last bandwith in error) to calculate ,it can run .  Whether the last bandwith in the error is the best bandwidth ? whether i can use the bandwith(the last bandwith in error) to calculate?

Best regards，
Jianbin

**Comment by sevengu11s** [comment]
Hello @binbin110 . I'm having the same problem and would like to know how you solved it. Thanks!
