### ISSUE TITLE
Enquiry: When to use mgwr or spreg?

### ISSUE THREAD

**Issue by iki77** [pysal/mgwr#95]
I'm a newbie in spatial model, can anyone explain to me
-  The difference between mgwr and spreg
-  When to use mgwr or spreg

**Comment by ljwolf** [comment]
Great question, @iki77! 

I think the choice of package really just comes down to the choice of *method* you want to employ. 

## `mgwr`: effects can be different in different places

The `mgwr` package is solely focused on the estimation of "geographically-weighted regression" models. At a high level, these models fit individual regressions at each site in your data. Think of it like the local model only pays attention to the data that is near that site. This means that the estimated effects, like your intercepts and your slopes/betas, can change at every site in the map. This could mean that an estimated effect of, say, age on earnings is positive in some places, but negative in others. 

The `mgwr` package provides methods to identify what should be considered "near" for the local models to pay attention to (`Sel_Bw` classes), and also methods to estimate the local models once that has been determined (`GWR` and `MGWR` classes). The difference between `GWR` and `MGWR` is whether each variable, sometimes called a "smooth", is given its own definition of "near", or *bandwidth*. The `MGWR` model can use a different bandwidth for each variable, whereas the `GWR` model uses the same bandwidth for all variables. (you can also have some variables which are not included in the "local" specification, and must have the same values everywhere). 

Some good written examples/discussions are with [Oshan et al. (2019)](https://www.mdpi.com/2220-9964/8/6/269), who provides some code and explanation of the entire package or [Comber et al (forthcoming)](https://arxiv.org/pdf/2004.06070.pdf), who provides some thinking as to why/how to choose between different specifications.  

## `spreg`:  Don't model sites separately, since they interact

The `spreg` package is focused on the estimation of a few different kinds of models. These models, generally, are *not* MGWR-style models, and they "pay attention" to the entire map. However, their unique trait is generally that there is a *spatial effect* in play. For example, *spatial dependence* is a very common spatial effect. By *spatial dependence*, we generally mean that you cannot assume that sites are independent of one another. A classic example is the sales price of a house: if my house sells for a lot of money, my neighbor's house might increase in value, too, since it will be priced relative to mine. 

The name of this kind of specification (at least that considered in `spreg`) is a *simultaneous autoregressive model* (SAR model). When dependence is present in the outcome (*y* term) it is often called a "Spatial Lag" model (e.g. the `ML_Lag` or `GM_Lag` class), and when spatial dependence is present in the error term it is often called a "Spatial Error model" (e.g. the `ML_Error` or `GM_Error` classes). 

`spreg` also contains methods to deal with cases where your *variance* isn't the same across the map (some regions may have more variation than others, sometimes called *spatial heteroskedasticity*) and also cases where there are specific, known regions with different behavior (sometimes called "regime" models). Some good intros include [the chapter in @sjsrey, @darribas, and my forthcoming book](https://geographicdata.science/book/notebooks/11_regression.html), as well as the book by [Anselin & Rey](https://www.worldcat.org/title/modern-spatial-econometrics-in-practice-a-guide-to-geoda-geodaspace-and-pysal/oclc/907551470).

**Comment by ljwolf** [comment]
I should also say, deciding what model to use will depend on the *question you're seeking to answer*, and that question generally will implicate one of these sets of methods! GWR models are all about the fact that your estimated relationships can change smoothly over space. spreg models are more diverse, but generally are useful when you're just interested in the classic OLS-type models, but spatial interaction or structure is getting "in the way," so to speak.

**Comment by iki77** [comment]
Thanks for the explanation @ljwolf 
It's easy to understand
